server:
  port: 8082
databases:
  - user: admin
    password: admin
    host: localhost
    dbName: shopDEV
  - user: admin2
    password: admin2
    host: localhost
    dbName: order
security:
  jwt:
    key: abc123