server:
  port: 8082
  mode: "dev"
mysql:
  host: 127.0.0.1
  port: 3306
  username: king
  password: king
  dbname: shopdevgo
  maxIdleCons: 10
  maxOpenConns: 100
  connMaxLifetime: 3600
  connMaxIdleTime: 10
log:
  log_level: debug
  file_log_name: ./storages/logs/dev.001.log
  max_size: 500
  max_backups: 3
  max_age: 28
  compress: true
redis:
  host: 127.0.0.1
  port: 6379
  password:
  database: 0
  poolsize: 10
